
export enum UserRole {
  ADMIN = 'Admin',
  TEACHER = 'Teacher',
  PARENT = 'Parent',
  STUDENT = 'Student',
  GUEST = 'Guest'
}

export enum View {
  // Auth
  LOGIN = 'LOGIN',

  // Teacher Views
  TEACHER_DASHBOARD = 'TEACHER_DASHBOARD',
  TEACHER_QUIZ_CONFIG = 'TEACHER_QUIZ_CONFIG',
  TEACHER_QUIZ_SHARE = 'TEACHER_QUIZ_SHARE',
  TEACHER_QUIZ_RESULTS = 'TEACHER_QUIZ_RESULTS', // Added
  TEACHER_REPORT_ENTRY = 'TEACHER_REPORT_ENTRY',
  TEACHER_ASSIGNMENTS = 'TEACHER_ASSIGNMENTS',
  TEACHER_ATTENDANCE = 'TEACHER_ATTENDANCE',

  // Admin Views
  ADMIN_DASHBOARD = 'ADMIN_DASHBOARD',
  ADMIN_REGISTRATION = 'ADMIN_REGISTRATION',
  ADMIN_FEES = 'ADMIN_FEES',
  ADMIN_CALENDAR = 'ADMIN_CALENDAR',
  ADMIN_APPROVALS = 'ADMIN_APPROVALS',
  ADMIN_SETTINGS = 'ADMIN_SETTINGS',
  ADMIN_AUDIT_LOGS = 'ADMIN_AUDIT_LOGS',
  ADMIN_ANNOUNCEMENTS = 'ADMIN_ANNOUNCEMENTS',

  // Parent Views
  PARENT_DASHBOARD = 'PARENT_DASHBOARD',
  PARENT_FEES = 'PARENT_FEES',
  PARENT_ASSIGNMENTS = 'PARENT_ASSIGNMENTS',
  PARENT_REPORTS = 'PARENT_REPORTS',
  PARENT_REPORT_DETAIL = 'PARENT_REPORT_DETAIL',

  // Student Views
  STUDENT_QUIZ = 'STUDENT_QUIZ',
  
  // Guest
  GUEST = 'GUEST'
}

export interface User {
  name: string;
  role: UserRole;
  avatar: string;
}
